apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: maciej
spec:
  groups:
  - system:authenticated
  request:  # replace with output from shell command: cat maciej.csr | base64 | tr -d '\n'
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth