apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nbvh-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: bug.127.0.0.1.nip.io
    http:
      paths:
      - path: /?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: helloapp-nbvh-nohost-svc
            port:
              number: 8080
  - host: demo.127.0.0.1.nip.io
    http:
      paths:
      - path: /host/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: helloapp-nbvh-host-svc
            port: 
              number: 80
      - path: /echo/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: helloapp-nbvh-echo-svc
            port:
              number: 8080
      - path: /?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name:  helloapp-nbvh-dumpster-svc
            port:
              number: 80