FROM gradle:9.6-jdk21 AS builder
USER root
RUN mkdir -p /app
WORKDIR /app
COPY build.gradle ./
ADD src ./src
RUN gradle build

FROM eclipse-temurin:21-jre-alpine
COPY --from=builder /app/build/libs/gs-spring-boot-docker-0.1.0.jar .
EXPOSE 8080/tcp
ENTRYPOINT [ "java", "-jar", "./gs-spring-boot-docker-0.1.0.jar"]
