apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicate-my-app
  labels:
    some: other-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp-pod-new
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: nginx