apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: users-readonly
subjects:
- kind: ServiceAccount
  name: maciek
  namespace: maciek
roleRef:
  kind: ClusterRole 
  name: view
  apiGroup: rbac.authorization.k8s.io
