apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fanout-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /host/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: helloapp-fanout-host-svc
            port:
              number: 80
      - path: /echo/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: helloapp-fanout-echo-svc
            port:
              number: 8080