FROM python:3-slim

WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY *.py .
COPY api ./api

ENV LOG_LEVEL=INFO
EXPOSE 5002

CMD [ "python", "main.py" ]